{
 "title": "Kubernetes / Pod",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Cluster",
    "query": "infra,main,proxy,malta,casino-b2b,develop"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{source=\"$source\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", source=\"$source\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "POD Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pod Status",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}) by(namespace, pod, phase)) by(phase)",
       "legendFormat": "{{ phase }}"
      }
     ]
    }
   ]
  },
  {
   "title": "POD Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(container)(cluster_namespace_controller_pod_container:cpu_usage:rate{cluster=\"$source\",namespace=\"$namespace\",container!=\"\",pod=~\"$pod\",container=~\"$container\"}) / 1000",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{source=\"$source\",resource=\"cpu\",namespace=~\"$namespace\",pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{source=\"$source\",resource=\"cpu\",namespace=~\"$namespace\",pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{cluster=\"$source\",namespace=~\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"\"}[$__rate_interval])) by (container)",
     "legendFormat": "Throttled: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(container) (cluster_namespace_controller_pod_container:memory_working_set:bytes{cluster=\"$source\",namespace=\"$namespace\",container!~\"|POD\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{source=\"$source\",namespace=\"$namespace\",resource=\"memory\",pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{source=\"$source\",namespace=\"$namespace\",resource=\"memory\",pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Limit: {{ container }}"
    },
    {
     "expr": "rate(container_memory_failures_total{source=\"$source\",namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\",container!~\"|POD\",failure_type=\"pgfault\"}[2m])",
     "legendFormat": "MemPgFault: {{ container }}"
    }
   ]
  },
  {
   "title": "Network Usage packet in/out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{source=\"$source\",namespace=\"$namespace\",pod=~\"$pod\",interface=~\"eth0\"}[5m])) BY (pod,interface)",
     "legendFormat": "TX : {{ pod }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{source=\"$source\",namespace=\"$namespace\",pod=~\"$pod\",interface=~\"eth0\"}[5m])) BY (pod,interface)",
     "legendFormat": "RX : {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Usage rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{source=\"$source\",namespace=\"$namespace\",pod=~\"$pod\",interface=~\"eth.*\"}[5m])) BY (pod,interface)",
     "legendFormat": "TX : {{ pod }}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{source=\"$source\",namespace=\"$namespace\",pod=~\"$pod\",interface=~\"eth.*\"}[5m])) BY (pod,interface)",
     "legendFormat": "RX : {{ pod }}"
    }
   ]
  },
  {
   "title": "Disk R/W iops",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{source=\"$source\",namespace=\"$namespace\",pod=\"$pod\"}[2m]))by(device,pod)",
     "legendFormat": "{{pod}} - {{device}}: read_iops"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{source=\"$source\",namespace=\"$namespace\",pod=\"$pod\"}[2m]))by(device,pod)",
     "legendFormat": "{{pod}} - {{device}}: write_iops"
    }
   ]
  },
  {
   "title": "Disk R/W rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{source=\"$source\",namespace=\"$namespace\",pod=\"$pod\"}[2m]))by(device,pod)",
     "legendFormat": "{{pod}} - {{device}}: read_iops"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{source=\"$source\",namespace=\"$namespace\",pod=\"$pod\"}[2m]))by(device,pod)",
     "legendFormat": "{{pod}} - {{device}}: write_iops"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(container_sockets{source=\"$source\",namespace=\"$namespace\",pod=\"$pod\"}) by(device,pod)",
     "legendFormat": "sockets: {{pod}}"
    },
    {
     "expr": "sum(container_file_descriptors{source=\"$source\",namespace=\"$namespace\",pod=\"$pod\"}-container_sockets{source=\"$source\",namespace=\"$namespace\",pod=\"$pod\"}) by(device,pod)",
     "legendFormat": "files: {{pod}}"
    },
    {
     "expr": "max(container_ulimits_soft{source=\"$source\",namespace=\"$namespace\",pod=\"$pod\",ulimit=\"max_open_files\"}) by(device,pod)",
     "legendFormat": "ulimits: {{pod}}"
    }
   ]
  }
 ]
}