{
 "title": "PostgreSQL Queries Overview",
 "description": "PostgreSQL Queries Overview Dashboard",
 "tags": [ "PostgreSQL" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(pg_up,kubernetes_namespace)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{kubernetes_namespace=\"$namespace\", datname!~\"template.*\", kubernetes_pod_name=\"$Pod\"},datname)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pg_up{kubernetes_namespace=\"$namespace\"},kubernetes_pod_name)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$Pod\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Statements Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Statements Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_statements_calls{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\"}[$interval]) or \nirate(pg_stat_statements_calls{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\"}[5m])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Most Called Queries",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(topk(50,rate(pg_stat_statements_calls{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\",query=~\"^SELECT.*|^UPDATE.*|^INSERT.*\"}[$interval]) or \nirate(pg_stat_statements_calls{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\",query=~\"^SELECT.*|^UPDATE.*|^INSERT.*\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slowest Queries - Average Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Duration of Queries",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_statements_time_milliseconds{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\"}[$interval]) or \nirate(pg_stat_statements_time_milliseconds{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\"}[5m])) > 0)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Average Runtime (top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_statements_time_milliseconds{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\"}[$interval]) / \n(rate(pg_stat_statements_calls{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Most time consuming queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time spent in queries in last hour (top 50)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(topk(50,increase(sum(pg_stat_statements_time_milliseconds{query=~\"^SELECT.*|^INSERT.*|^UPDATE.*\",datname!=\"postgres\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\"}) by (query,queryid,user)[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest logs with long running queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Resent logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\",pod=\"$Pod\"} |~ \"duration:\""
    }
   ]
  },
  {
   "title": "Shared Blocks I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Shared Blocks Dirtied",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_dirtied{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\"}[$interval]))",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total Shared Blocks Catch Hits",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_hit{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\"}[$interval]))",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Top Shared Blocks  Dirtied",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_dirtied{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Shared Block Cache Hits",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_hit{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Shared Blocks Read",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_read{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\"}[$interval]))",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total Shared Blocks Written",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_written{datname=~\"$datname\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$Pod\"}[$interval]))",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Top Shared Blocks Read",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_read{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Shared Blocks Written",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}