{
 "title": "PostgreSQL PGbouncer Copy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Cluster", "query": "main,malta,casino-b2b" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pgbouncer_exporter_build_info{source=\"$source\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "db",
    "label": "Db",
    "query": {
     "query": "label_values(pgbouncer_exporter_database_current_connections{source=\"$source\", app_kubernetes_io_instance=\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client connections number",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_exporter_pools_active_clients{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Server connections number",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer_exporter_pools_active_server{source=\"$source\",app_kubernetes_io_instance=\"$instance\"}) + sum(pgbouncer_exporter_pools_idle_server{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active clients connected",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (pgbouncer_exporter_pools_active_clients{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server connections pool size (active + idle)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (pgbouncer_exporter_pools_active_server{source=\"$source\",app_kubernetes_io_instance=\"$instance\"} + pgbouncer_exporter_pools_idle_server{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server connections that are unused and immediately usable for client queries (Idle) vs Max Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgbouncer_exporter_pools_idle_server{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(pgbouncer_exporter_lists_items{list=~\"used_servers|free_servers\",app_kubernetes_io_instance=\"pgbouncer-exporter-promotion\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server connections that are linked to a client (active)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pgbouncer_exporter_pools_active_server{app_kubernetes_io_instance=\"$instance\",source=\"$source\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Clients vs Server connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(list) (pgbouncer_exporter_lists_items{source=\"$source\",app_kubernetes_io_instance=\"$instance\",list=\"used_clients\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(list) (pgbouncer_exporter_lists_items{source=\"$source\",app_kubernetes_io_instance=\"$instance\",list=\"used_servers\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (pgbouncer_exporter_pools_active_server{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})",
     "legendFormat": "active_servers"
    }
   ]
  },
  { "title": "SQL queries and transacions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Total SQL transactions rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sort_desc( sum by (database, hostname) ( rate(pgbouncer_exporter_stats_total_xact_count{source=\"$source\",app_kubernetes_io_instance=\"$instance\"}[1m]) ) )  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total SQL queries rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sort_desc( sum by (database, hostname) ( rate(pgbouncer_exporter_stats_total_query_count{source=\"$source\",app_kubernetes_io_instance=\"$instance\"}[1m]) ) )  ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Different", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Pgbouncer pools connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (user) (pgbouncer_exporter_pools_active_clients{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (user) (pgbouncer_exporter_pools_waiting_clients{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (app_kubernetes_io_instance) (pgbouncer_exporter_database_pool_size{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (user) (pgbouncer_exporter_pools_active_server{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (user) (pgbouncer_exporter_pools_idle_server{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (user) (pgbouncer_exporter_pools_used_server{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "How long the first (oldest) client in the queue has waited, in seconds",
   "type": "timeseries",
   "description": "If this starts increasing, then the current pool of servers does not handle requests quickly enough. The reason may be either an overloaded server or just too small of a pool_size setting.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(user) (pgbouncer_exporter_pools_used_server{source=\"$source\",app_kubernetes_io_instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}